id: P009627
initial_creation_type: ocr
source_metadata:
  id: bdr:W19999
  title: དགེ་ལུགས་པའི་ཆོས་སྤྱོད་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    4d3c9078a95b43c1a258de7892df2f18:
      image_group_id: I1PD86093
      title: ''
      volume_number: 1
      total_pages: 164
    4d179b941b8c41be97733c1cfcb74d49:
      image_group_id: I1PD86094
      title: ''
      volume_number: 2
      total_pages: 169
    d8f868fa1ac5430fbabd2d2f21a55e8c:
      image_group_id: I1PD86095
      title: ''
      volume_number: 3
      total_pages: 232
    fcb8e586a10d49f99f465f47071553a2:
      image_group_id: I1PD86096
      title: ''
      volume_number: 4
      total_pages: 230
    85941fb81b5044c1b9caeb238ae2149b:
      image_group_id: I1PD86097
      title: ''
      volume_number: 5
      total_pages: 206
    7ac2629382dd47969498c727ca5fa529:
      image_group_id: I1PD86098
      title: ''
      volume_number: 6
      total_pages: 154
