id: I37B14CF7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:19:06+00:00'
last_modified: '2022-06-08T12:22:16.005230+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19999
  title: དགེ་ལུགས་པའི་ཆོས་སྤྱོད་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4944':
      image_group_id: I1PD86093
      title: ''
      total_pages: 164
      order: 1
      base_file: 4944.txt
    FEC3:
      image_group_id: I1PD86094
      title: ''
      total_pages: 169
      order: 2
      base_file: FEC3.txt
    030C:
      image_group_id: I1PD86095
      title: ''
      total_pages: 232
      order: 3
      base_file: 030C.txt
    DB43:
      image_group_id: I1PD86096
      title: ''
      total_pages: 230
      order: 4
      base_file: DB43.txt
    69C9:
      image_group_id: I1PD86097
      title: ''
      total_pages: 206
      order: 5
      base_file: 69C9.txt
    B7B5:
      image_group_id: I1PD86098
      title: ''
      total_pages: 154
      order: 6
      base_file: B7B5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
